version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

aliases:
- &ssh-fingerprint
    fingerprints:
      - "ae:83:a5:6c:93:c9:16:57:ec:21:b9:6f:9c:5a:10:9c"
- &install-dependencies
  name: Install Node Dependencies
  command: npm install
- &test
  name: Test
  command: npm run test
- &build
  name: Build
  command: npm run build
- &save-dependency-cache
  paths:
  - node_modules
  key: node_modules-v2-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
- &restore-dependency-cache
  name: Restore dependency cache
  keys:
  - node_modules-v2-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
  - node_modules-v2-{{ arch }}-

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
    - checkout
    - restore_cache: *restore-dependency-cache
    - run: *install-dependencies
    - save_cache: *save-dependency-cache
    - run: *test
    - run: *build
    - sonarcloud/scan:
        sonar_token_variable_name: ENTUR_SONAR_PASSWORD
    - store_test_results:
        path: junit.xml
workflows:
  install-test-build:
    jobs:
    - build:
        name: npm-build
        context: global
        filters:
          branches:
            only:
            - master
